### ISSUE TITLE
PyPI 0.0.1 release git commit

### ISSUE THREAD

**Issue by zzhengnan** [coiled/dask-snowflake#10]
Hi team. Thanks for this inspired tool! I'm really excited about integrating Dask with Snowflake.

I understand there's a 0.0.1 release for this package on PyPI but don't see a corresponding git tag in this repo. Can you point me to the exact commit? Thanks!

https://pypi.org/project/dask-snowflake/0.0.1/

**Comment by zzhengnan** [comment]
@jrbourbeau I see version 0.0.2 was just uploaded to PyPI (and a corresponding tag created here on GitHub). Is this version appropriate for general testing/usage? 

Separately, is there anything you can share regarding the future of this project in terms of planned features etc. Thanks!

**Comment by jrbourbeau** [comment]
Yep! Version 0.0.2 on PyPI (and conda-forge) should be good to start testing out. Any feedback you have is very welcome : )

> Separately, is there anything you can share regarding the future of this project in terms of planned features etc.

`dask-snowflake` is meant to provide an interface between Snowflake and Dask for parallel IO. Are there specific features you're looking for? For example, having control over the partition batch size fetched from Snowflake has come up before (xref https://github.com/coiled/dask-snowflake/issues/7)

**Comment by zzhengnan** [comment]
I don't have anything particular in mind. Was mostly just curious about the future direction of the project.

I look forward to testing this out for some projects at work. Will definitely check back in if I have any feedback. Thanks James!
