### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by fjetter** [coiled/dask-snowflake#5]
Title says it all

**Comment by ian-r-rose** [comment]
:+1: from me. In addition to all the usual good reasons, my muscle memory has switched at this point and it was causing some friction when working with this repo yesterday :)

**Comment by jrbourbeau** [comment]
Just updated the default branch to `main`. GitHub says this is how one should handle branch migration:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
