### ISSUE TITLE
Partition size as argument for read_snowflake

### ISSUE THREAD

**Issue by fjetter** [coiled/dask-snowflake#7]
The performance of a lot of dask workflows are highly sensitive to partition sizes. Currently we see a lot of the result batches from snowflake to be small and a repartitioning should improve downstream performance. As a user I would like to have an easy way to control this when reading data from snowflake.

While the snowflake backend currently doesn't expose this as an option, it _should_ (currently buggy, waiting for response on bug report) provide partition level size statistics. Using this statistics we should be able to implement a fast size based repartitioning and offer this as a read argument, e.g.

```python

read_snowflake(query=..., ..., partition_size="100MB")
```

**Comment by mrocklin** [comment]
@fjetter do we get information from snowflake on the size of their partitions?  Maybe we can batch these up on our end and have one task read many partitions?

**Comment by fjetter** [comment]
> do we get information from snowflake on the size of their partitions? 

Theoretically (currently a bit buggy) we get row count, compressed and uncompressed size and we could do some simple bin packing. My first draft included this already but I removed it again because it was not reliable. we could already start implementing the logic, though, and once the connector is released we can enable it.

**Comment by fjetter** [comment]
For the interested reader. A simple way to do this yourself, but less accurately, is to read a dataframe and perform some repartitioning yourself, e.g.

```python
ddf = read_snowflake(...)
ddf = ddf.repartition(npartitions=ddf.npartitions // 2)
```

That's not optimal but should already speed things up. You are free to experiment with the factor 2 or you might want to consider using another option of [DataFrame.repartition](https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.repartition.html#dask.dataframe.DataFrame.repartition)

**Comment by mrocklin** [comment]
@mdwgrogan you were running into this as well, is that correct?

**Comment by mdwgrogan** [comment]
Yes. I implemented a way to do this using the rowcount but using an actual size value would probably be better.

**Comment by mrocklin** [comment]
@jrbourbeau can I ask your team to own this?

My guess is that this also affects another workflow we've see recently.

**Comment by mrocklin** [comment]
@mdwgrogan if you have time to test this out that would be welcome
